//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tick.DAL.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.ExpensesTrackings = new HashSet<ExpensesTracking>();
        }
    
        public int CategoryID { get; set; }
        public bool IsExpenses { get; set; }
        public string Name { get; set; }
        public int InsertBy { get; set; }
        public System.DateTime InserDate { get; set; }
        public Nullable<int> LUB { get; set; }
        public Nullable<int> LUN { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesTracking> ExpensesTrackings { get; set; }
    }
}
