//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tick.DAL.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesTracking
    {
        public int ETrackingID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int InsertBy { get; set; }
        public System.DateTime InserDate { get; set; }
        public Nullable<int> LUB { get; set; }
        public Nullable<int> LUN { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
