//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tick.DAL.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ExpensesTrackings = new HashSet<ExpensesTracking>();
            this.TimeTrackings = new HashSet<TimeTracking>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public int Role { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int InsertBy { get; set; }
        public System.DateTime InserDate { get; set; }
        public Nullable<int> LUB { get; set; }
        public Nullable<int> LUN { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesTracking> ExpensesTrackings { get; set; }
        public virtual Role Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTracking> TimeTrackings { get; set; }
    }
}
